### ISSUE TITLE
(bug) 1.19.2: terracotta water bowls wont go past slightly acceptable when placed on campfire

### ISSUE THREAD

**Issue by jumble67** [ghen-git/Thirst-Mod#52] opened 2023-08-25 07:13 UTC
i discovered a bug when using a terracotta bowl. i used it to get dirty water from a source block in a regular body of water. it purifies once on a campfire to slightly dirty, but wont go past that no matter how many times it is placed on the campfire. water bottles don't have this issue and can be fully purified on a campfire. terracotta bowls can be fully purified in a furnace so its just the campfire with this issue (if it is an intended feature i'm sorry, feel free to take this post down)

**Comment by mlus-asuka** [comment] 2023-08-25 11:50
this is supposed to fix in the newest version. are you using 1.3.1?

**Comment by jumble67** [comment] 2023-08-25 12:40
yes i am using version 1.3.1 on forge 1.19.2

**Comment by mlus-asuka** [comment] 2023-08-25 13:26
I just tested right now. but it seems work well. what I know is this bug was present at past because I added surplus blanks in the recipe json

**Comment by ghen-git** [comment] 2023-08-25 13:34
oh no, its true, i'll try and figure out what the issue is, thanks for the report @jumble67

**Comment by ghen-git** [comment] 2023-08-25 15:00
the bug is fixed in the patch `1.3.2`, it'll come out in a few mins

**Closed as completed by ghen-git** 2023-08-25 15:00 UTC
