### ISSUE TITLE
[Bug] [1.18.2] Failed to Load as Forge Server Mod

### ISSUE THREAD

**Issue by Silverlehs** [ghen-git/Thirst-Mod#3] opened 2022-10-12 22:40 UTC
I get the following error when trying to load the mod into a server (tried it by itself):

Mod Version: Thirst-1.18.2-1.1.1
Forge Version: 40.1.74
[
Thirst Mod (thirst) has failed to load correctly
?7java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
]

I'm not certain but is it pertaining to how the player network data is coded here? 
src/main/java/dev/ghen/thirst/foundation/network/message/PlayerThirstSyncMessage.java

Great work, really awesome mod!

**Comment by ghen-git** [comment] 2022-10-15 11:29
Ohh yeah, i'll fix it asap. Technically a new patch should be up by today. Will update this thread when the issue is fixed

**Comment by ghen-git** [comment] 2022-10-15 11:35
I'm glad you're using it on a server btw, happy you enjoy it!
i'll fix the issue asap

**Comment by ghen-git** [comment] 2022-10-15 12:24
Fixed with the new patch, should be available to download in minutes

**Closed by ghen-git** 2022-10-15 12:24 UTC
